# Generated by Django 4.0.4 on 2022-05-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=20, unique=True)),
                ('quantity_enabled', models.BooleanField()),
                ('quantity', models.IntegerField()),
                ('status', models.IntegerField()),
                ('date_assigned', models.DateTimeField()),
                ('date_due', models.DateTimeField(null=True)),
            ],
        ),
    ]
