# Generated by Django 4.0.4 on 2022-05-25 17:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PartTrackerApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter_Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=20, unique=True)),
                ('quantity_enabled', models.BooleanField(default=True)),
                ('quantity', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_due', models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Workspace',
        ),
    ]
