# Generated by Django 4.0.4 on 2022-05-25 17:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PartTrackerApp', '0002_filter_tasks_delete_workspace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter_tasks',
            name='quantity_enabled',
        ),
        migrations.AlterField(
            model_name='filter_tasks',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
