# Generated by Django 4.0.4 on 2022-05-25 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PartTrackerApp', '0003_remove_filter_tasks_quantity_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parts_List_Range',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upper', models.IntegerField(default=0)),
                ('lower', models.IntegerField(default=20)),
            ],
        ),
    ]
